### ISSUE TITLE
bouton mail

### ISSUE THREAD

**Issue by NicolasHuraux** [RemyTrohel/WildersBook#3]
bouton mail qui ne fonctionne pas, peut etre l enlever ?

**Comment by rocambille** [comment]
vous pouvez vous inspirez de vos copains js ;)

https://github.com/Dezedene/R1S_0219_BOOKWILDERS/blob/6cc54c5b6c03b4c4a13dded2b234685625a26791/script.js#L255

avec le code html :

https://github.com/Dezedene/R1S_0219_BOOKWILDERS/blob/6cc54c5b6c03b4c4a13dded2b234685625a26791/script.js#L156

**Comment by RemyTrohel** [comment]
**Fixed** : mailto remplacé par un script de copie du mail
